### ISSUE TITLE
allow passing arguments to AnyEvent::WebSocket::Server->new

### ISSUE THREAD

**Issue by mephinet** [debug-ito/Plack-App-WebSocket#3]
`AnyEvent::WebSocket::Server` takes two arguments to its constructor, `handshake` and `validator`. Unfortunately, `Plack::App::WebSocket`'s new method does not allow passing any arguments to `AnyEvent::WebSocket::Server`, so if a callback is needed, it needs to be monkey-patched into the instance after construction.

**Comment by debug-ito** [comment]
Yeah, that is an obvious need. I'll tackle on that issue.

**Comment by debug-ito** [comment]
Released version 0.05

**Comment by mephinet** [comment]
perfect, thanks!
